name: Convert CV to Markdown

on:
  push:
    paths:
      - 'Sofiya_CV.tex'
  workflow_dispatch: 

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert LaTeX to Markdown
        run: |
          echo "---" > cv.md
          echo "layout: page" >> cv.md
          echo "title: Curriculum Vitae" >> cv.md
          echo "permalink: /cv/" >> cv.md
          echo "---" >> cv.md
          

          echo '<div style="max-width: 1000px; margin: 40px auto; line-height: 1.8; padding: 40px; border: 1px solid #efefef; background: #fff; color: #333;">' >> cv.md
          echo "" >> cv.md
          
          pandoc Sofiya_CV.tex --from latex+raw_tex --to gfm --wrap=preserve >> cv.md
          
          echo "" >> cv.md
          echo '</div>' >> cv.md

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cv.md
          git commit -m "Fixing CV spacing and formatting" || exit 0
          git push
