name: Convert CV to Markdown

on:
  push:
    paths:
      - 'Sofiya_CV.tex'
  workflow_dispatch: 

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert LaTeX to Markdown
        run: |
          echo "---" > cv.md
          echo "layout: page" >> cv.md
          echo "title: Curriculum Vitae" >> cv.md
          echo "permalink: /cv/" >> cv.md
          echo "---" >> cv.md
          echo "" >> cv.md
          
          echo '<style>
            #main, .page, .page__inner-wrap, .archive { 
              max-width: 1000px !important; 
              margin-left: auto !important; 
              margin-right: auto !important; 
              padding-right: 0 !important;
            }
          </style>' >> cv.md
          echo "" >> cv.md
          
          pandoc Sofiya_CV.tex -f latex -t markdown_strict >> cv.md

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cv.md
          git commit -m "Auto-update CV: constrained for academicpages" || exit 0
          git push
