name: Sync Google Scholar

on:
  schedule:
    - cron: '0 0 * * 4' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Fetch Scholar Data
        uses: xf-97/academic-scholar@v1.0
        with:
          scholar_id: '7ZBuO4wAAAAJ'
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p data
          git add data/scholar.json
          git commit -m "Update Scholar citations" || exit 0
          git push
